export const API_KEY = "2bfe51616ff2e3e507aaba017be457f9"
export const baseURL = "https://api.themoviedb.org/3"
export const imageURL = "https://image.tmdb.org/t/p/original"
export const navBarImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/1920px-Netflix_2015_logo.svg.png"
export const bannerFilmDetails = "trending/all/week?api_key="+API_KEY+"&language=en-US"
export const originals = "discover/tv?api_key="+API_KEY+"&with_networks=213"